# Generated by Django 5.1.1 on 2025-03-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('confirmation', models.CharField(max_length=20)),
            ],
        ),
    ]
