# Generated by Django 5.1.1 on 2025-03-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0002_create_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('confirmation', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='create_ticket',
        ),
    ]
