# Generated by Django 5.1.7 on 2025-03-20 00:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0005_createticket_receipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('members', models.ManyToManyField(blank=True, related_name='organizations', to=settings.AUTH_USER_MODEL)),
                ('pending_members', models.ManyToManyField(blank=True, related_name='pending_organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
