# Generated by Django 5.1.1 on 2025-03-18 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0005_createticket_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='createticket',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='createticket',
            name='confirmation',
        ),
        migrations.AddField(
            model_name='createticket',
            name='expense_category',
            field=models.CharField(choices=[('supplies', 'Supplies'), ('reimbursements', 'Reimbursements'), ('food', 'Food'), ('travel', 'Travel'), ('membershipfee', 'Membership Fee'), ('other', 'Other')], default='supplies', max_length=20),
        ),
        migrations.AddField(
            model_name='createticket',
            name='operation',
            field=models.CharField(choices=[('add', '+'), ('minus', '-')], default='add', max_length=20),
        ),
        migrations.AddField(
            model_name='createticket',
            name='custom_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FundFlow.customcategory'),
        ),
    ]
