# Generated by Django 5.1.1 on 2025-03-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0008_remove_fundingrequest_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createticket',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='createticket',
            name='confirmation',
        ),
        migrations.AddField(
            model_name='createticket',
            name='expense_category',
            field=models.CharField(choices=[('supplies', 'Supplies'), ('reimbursements', 'Reimbursements'), ('food', 'Food'), ('travel', 'Travel'), ('membershipfee', 'Membership Fee'), ('other', 'Other')], default='supplies', max_length=20),
        ),
        migrations.AddField(
            model_name='createticket',
            name='operation',
            field=models.CharField(choices=[('add', '+'), ('minus', '-')], default='add', max_length=20),
        ),
    ]
