# Generated by Django 5.1.1 on 2025-03-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0009_organization_president'),
        ('FundFlow', '0009_remove_createticket_balance_and_more'),
    ]

    operations = [
    ]
