# Generated by Django 5.1.7 on 2025-04-09 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0010_merge_20250326_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_Org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FundFlow.organization'),
        ),
    ]
