# Generated by Django 5.1.1 on 2025-04-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0011_userprofile_current_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='createticket',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
