# Generated by Django 5.1.1 on 2025-04-23 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0012_remove_organization_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='createticket',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundFlow.organization'),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fundingrequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundFlow.organization'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundFlow.organization'),
        ),
    ]
