# Generated by Django 5.1.1 on 2025-04-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0014_alter_createticket_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.FileField(blank=True, null=True, upload_to='merchIMG/')),
                ('supply', models.PositiveIntegerField()),
                ('tags', models.ManyToManyField(blank=True, to='FundFlow.tag')),
            ],
        ),
    ]
