# Generated by Django 5.1.1 on 2025-04-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0015_tag_createitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createitem',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='createitem',
            name='tags',
            field=models.TextField(default='All'),
        ),
    ]
