# Generated by Django 5.1.1 on 2025-04-28 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0016_remove_createitem_tags_delete_tag_createitem_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createitem',
            old_name='supply',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='createitem',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='FundFlow.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createitem',
            name='tags',
            field=models.CharField(choices=[('all', 'All'), ('membership', 'Membership'), ('tops', 'Tops'), ('bottoms', 'Bottoms'), ('hoodies', 'Hoodies'), ('hats', 'Hats'), ('clothing', 'Clothing'), ('pins', 'Pins'), ('tickets', 'Tickets'), ('holiday', 'Holiday')], default='All', max_length=20),
        ),
    ]
