# Generated by Django 5.1.1 on 2025-05-03 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0017_rename_supply_createitem_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateItem',
            new_name='Item',
        ),
    ]
