# Generated by Django 5.1.1 on 2025-05-03 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0018_rename_createitem_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
