# Generated by Django 5.1.7 on 2025-05-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0015_organization_treasurer'),
        ('FundFlow', '0020_remove_item_tags_item_tags'),
    ]

    operations = [
    ]
