# Generated by Django 5.1.7 on 2025-05-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0021_merge_20250503_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bank_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
    ]
