# Generated by Django 5.1.7 on 2025-05-06 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0021_poll_expiration_date_poll_pub_date'),
        ('FundFlow', '0022_organization_bank_email'),
    ]

    operations = [
    ]
