# Generated by Django 5.1.7 on 2025-05-07 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0022_poll_created_by_poll_organization'),
        ('FundFlow', '0023_merge_20250505_2013'),
    ]

    operations = [
    ]
