# Generated by Django 5.1.7 on 2025-05-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0024_merge_20250506_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='FundFlow.createticket'),
        ),
    ]
