# Generated by Django 5.1.7 on 2025-05-13 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0024_merge_20250506_2250'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundingrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='fundingrequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_funding_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fundingrequest',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funding_requests', to='FundFlow.organization'),
        ),
    ]
