# Generated by Django 5.1.7 on 2025-05-13 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FundFlow', '0025_organization_tickets'),
        ('FundFlow', '0025_remove_fundingrequest_user_fundingrequest_created_by_and_more'),
    ]

    operations = [
    ]
